[package]
name = "monotonic"
version = "0.1.0"
authors = ["Henrik Tj√§der <henrik@tjaders.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-error = "1"
quote = "1"
syn = "1"
